
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module bmr_tdee(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////////// KEY //////////
	KEY,

	//////////// SW //////////
	SW 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;

//////////// LED //////////
output		     [7:0]		LED;

//////////// KEY //////////
input 		     [1:0]		KEY;

//////////// SW //////////
input 		     [3:0]		SW;


//=======================================================
//  REG/WIRE declarations
//=======================================================

bmr_tdee_qsys bmr_tdee_inst(
		.pio_led_external_connection_export(LED), // pio_led_external_connection.export
		.pio_sw_external_connection_export(SW),  //  pio_sw_external_connection.export
		.reset_reset_n(1'b1),                      //                       reset.reset_n
		.clk_clk(CLOCK_50),                            //                         clk.clk
		.pio_bt_external_connection_export(KEY)   //  pio_bt_external_connection.export
	);



//=======================================================
//  Structural coding
//=======================================================



endmodule
